# Generated by Django 5.2.1 on 2025-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='user.author'),
        ),
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('I', 'IGBO'), ('Y', 'YORUBA'), ('EN', 'ENGLISH'), ('FR', 'FRENCH'), ('ES', 'SPANISH'), ('IT', 'ITALIAN')], default='EN', max_length=2),
        ),
    ]
